### ISSUE TITLE
Cannot set property 'value' of undefined

### ISSUE THREAD

**Issue by magicspon** [jonathantneal/postcss-transform-shortcut#8]
Hello, 

I'm getting the following error when I try and use this plugin:

```
[13:14:40] Requiring external module babel-register
[13:14:42] Using gulpfile ~/websites/_mudstone/gulpfile.babel.js
[13:14:42] Starting 'sass'...

events.js:154
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot set property 'value' of undefined
    at /Users/stockley/websites/_mudstone/node_modules/postcss-transform-shortcut/index.js:44:20
    at /Users/stockley/websites/_mudstone/node_modules/postcss/lib/container.js:110:28
    at /Users/stockley/websites/_mudstone/node_modules/postcss/lib/container.js:73:26
    at Root.each (/Users/stockley/websites/_mudstone/node_modules/postcss/lib/container.js:60:22)
    at Root.walk (/Users/stockley/websites/_mudstone/node_modules/postcss/lib/container.js:72:21)
    at Root.walkRules (/Users/stockley/websites/_mudstone/node_modules/postcss/lib/container.js:108:25)
    at /Users/stockley/websites/_mudstone/node_modules/postcss-transform-shortcut/index.js:15:7
    at LazyResult.run (/Users/stockley/websites/_mudstone/node_modules/postcss/lib/lazy-result.js:206:20)
    at /Users/stockley/websites/_mudstone/node_modules/postcss/lib/lazy-result.js:120:37
    at LazyResult.asyncTick (/Users/stockley/websites/_mudstone/node_modules/postcss/lib/lazy-result.js:134:15)
    at processing.Promise.then._this2.processed (/Users/stockley/websites/_mudstone/node_modules/postcss/lib/lazy-result.js:160:20)
    at LazyResult.async (/Users/stockley/websites/_mudstone/node_modules/postcss/lib/lazy-result.js:157:27)
    at LazyResult.then (/Users/stockley/websites/_mudstone/node_modules/postcss/lib/lazy-result.js:79:21)
    at Transform.stream._transform (/Users/stockley/websites/_mudstone/node_modules/gulp-postcss/index.js:49:8)
    at Transform._read (_stream_transform.js:166:10)
    at Transform._write (_stream_transform.js:154:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Transform.Writable.write (_stream_writable.js:207:11)
    at DestroyableTransform.ondata (/Users/stockley/websites/_mudstone/node_modules/gulp-sourcemaps/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at emitOne (events.js:90:13)
    at DestroyableTransform.emit (events.js:182:7)
    at readableAddChunk (/Users/stockley/websites/_mudstone/node_modules/gulp-sourcemaps/node_modules/readable-stream/lib/_stream_readable.js:198:18)
    at DestroyableTransform.Readable.push (/Users/stockley/websites/_mudstone/node_modules/gulp-sourcemaps/node_modules/readable-stream/lib/_stream_readable.js:157:10)
    at DestroyableTransform.Transform.push (/Users/stockley/websites/_mudstone/node_modules/gulp-sourcemaps/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at DestroyableTransform.sourceMapInit [as _transform] (/Users/stockley/websites/_mudstone/node_modules/gulp-sourcemaps/index.js:21:12)
    at DestroyableTransform.Transform._read (/Users/stockley/websites/_mudstone/node_modules/gulp-sourcemaps/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/stockley/websites/_mudstone/node_modules/gulp-sourcemaps/node_modules/readable-stream/lib/_stream_transform.js:147:83)
```

My gulp task looks like this:

```
... etc etc ... 
import independentTransforms from 'postcss-transform-shortcut';

gulp.task('sass', () => {
  return gulp.src($sass.watch)
    .pipe(sourcemaps.init())
    .pipe(sass({
        outputStyle: $sass.options.outputStyle,
        includePaths
      }
    ))
    .on('error', handleErrors)
    .pipe(sourcemaps.write({includeContent: false}))
    .pipe(sourcemaps.init({loadMaps: true}))
    .pipe(postcss([ 
        autoprefixer({ browsers: $sass.prefix }),
        independentTransforms 
        ]))
    .pipe(sourcemaps.write('./'))
    .on('error', handleErrors)
    .pipe(gulp.dest($sass.dest))
    // .pipe(browserSync.reload({stream:true}));
});
```

Where am I going wrong?  Thanks

**Comment by jonathantneal** [comment]
I’ve pushed some significant updates. Would you check again?
